name: ci

on: [push, pull_request]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: download
        run: |
          git config --local user.email "dreamingclear@163.com"
          git config --local user.name "lyxy"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          ./bin/youtube-dl --config-location config.txt
          git add .
          git commit -m "download youtube video"
          git push
